### ISSUE TITLE
function ref sections

### ISSUE THREAD

**Issue by schloerke** [schloerke/packagedocs#1]
@hafen

if I have 

```
#' Test file
#'
#' @param a test param number 1
#' @param b test param number 2
#' @rdname test_fn
#' @examples
#' test_fn_a(4)
#' test_fn_b("world")
test_fn_a <- function(a) {
  a
}

#' @rdname test_fn
test_fn_b <- function(b) {
  b
}
```

Should it produce a function topic for each function or just the alias?

I'm leaning towards just the alias as the functions are grouped together for a reason.

**Comment by hafen** [comment]
That's a good question.  I like having each show up as a separate entity in the table of contents with the actual function name (the alias is not always helpful) but it is kind of silly to repeat the docs for each one.  What do you think?

**Comment by schloerke** [comment]
My thought is to make one section, rather than two copies.

There must have been a reason to combine the docs under one alias in the first place. If they want it to be repeated, then they can have different docs for each function.

**Comment by hafen** [comment]
I think that's good.  However, it is much more meaningful for the actual function names to show up in the table of contents so if we can have one section but multiple pointers to it in the TOC, that would be good.  But then there wouldn't be a linear procession through the TOC as you scroll.  Take for example `@rdname unit_conversion` in the hbgd package.  To me it is much more meaningful for the TOC to list out all the function names `cm2in`, `lb2kg`, etc. (so that the reader can see everything that is actually available) rather than have a listing `unit_conversion` which doesn't mean anything.  Any ideas?

**Comment by schloerke** [comment]
I think I've come up with a good compromise.

It only displays the docs once, as breaking up the usage and information does not seem right.  However, the title is autogenerated in the init method to be "ALIAS_NAME: fn1, fn2, fn3".  Visually this seems to work well as there's a gap between items, but a small gap between lines if it has to wrap.

Example of hbgd package and hovering over one 'link' to the "igb_zscore2var" rd alias
![screen shot 2016-07-12 at 5 07 20 pm](https://cloud.githubusercontent.com/assets/93231/16783713/2b8ac0b0-4853-11e6-9437-e5640a743b54.png)
