### ISSUE TITLE
add lazy option to rd_index.yaml

### ISSUE THREAD

**Issue by hafen** [schloerke/packagedocs#12]
It would be nice to have the ability to make examples in the rd page lazily loaded.  We could follow the scheme used for whether to eval the example or not (of course for any chunk with eval=FALSE, lazy would be ignored)

```
knitr:
  eval: true
  lazy: true
```

**Comment by schloerke** [comment]
since lazyrmd only attaches files if lazy is TRUE, i'm switching to call lazyrmd::lazy_render.

This also allows for passing the `rmarkdown` arg from the vignette files to determine which rmarkdown renderer should be used.

such as...

```{yaml}
---
title: "packagedocs"
author: Barret Schloerke
output:
  packagedocs:
    toc: true
    rmarkdown: html_vignette
---
```

would call `rmarkdown::html_vignette` and not `rmarkdown::html_document`

**Comment by schloerke** [comment]
https://github.com/schloerke/packagedocs/compare/eb64368...37bcd10?expand=1
